[project]
name = "forecasting-platform"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "polars",
    "pandas",
    "numpy",
    "scikit-learn",
    "lightgbm",
    "matplotlib",
    "plotly",
    "pyarrow",
    "mlflow",
    "streamlit",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]